config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  
  root 'pages#home'

  get 'about' => 'pages#about'

  post '/compra/:slug', to: 'transactions#create', as: :compra

  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  get 'dashboard' => 'pages#dashboard'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  extend FriendlyId
  friendly_id :titolo, use: :slugged
	belongs_to :user
  has_many :sales

	has_attached_file :cover
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  	message: "Solo le immagini sono supportate"

  	has_attached_file :allegato 
  	validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
  	message: "Formato non supportato"

  	validates :titolo, :descrizione, :price, presence: true
  	validates :price, numericality: { greater_than: 0.49 }
  	validates :cover, attachment_presence: true
  	validates :allegato, attachment_presence: true
end

app/models/sale.rb
class Sale < ApplicationRecord
	before_create :generate_guid
	belongs_to :content

	include AASM

	aasm column: 'state' do
		state :sleeping, initial: true
    	state :running
    	state :completed
    	state :errored

    	event :running, after: :charge_card do
    		transitions from: :sleeping, to: :running
    	end

    	event :complete do
    		transitions from: :running, to: :completed
    	end

    	event :fail do
    		transitions from: :running, to: :errored
    	end
	end

    def charge_card
    	begin
    		save!
    		charge = Stripe::Charge.create(
    				amount: self.amount,
    				currency: "eur",
    				card: self.stripe_token,
    				description: "vendita di un contenuto"
    			)
    		self.update(stripe_id: charge.id)
    		self.complete!
    	rescue Stripe::StripeError => e
    		self.update_attributes(error: e.message)
    		self.fail!
    	end
    end

	private

		def generate_guid
			self.guid = SecureRandom.uuid()
		end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :store_location

	protected

  	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  	end

  	def store_location
  		return unless request.get?
  		if (request.path != "/users/sign_in" &&
	        request.path != "/users/sign_up" &&
	        request.path != "/users/password/new" &&
	        request.path != "/users/password/edit" &&
	        request.path != "/users/confirmation" &&
	        request.path != "/users/sign_out" &&
	        !request.xhr?) # don't store ajax calls
	      store_location_for(:user, request.fullpath)
    	end
  	end

  	def after_sign_in_path_for(resource)
		session[:previous_url] || root_path  		
  	end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all.order('created_at DESC').paginate(page: params[:page], per_page: 6)
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Il contenuto è stato creato con successo.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Il contenuto è stato aggiornato con successo.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Il contenuto è stato eliminato.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "Scusa ma non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
  	@contents = Content.all
  end

  def about
  end
  
  def dashboard
  	@content = current_user.contents
  	@sales = Sale.where(email_venditore: current_user.email)
  	@purchased = Sale.where(email_acquirente: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def create
		content = Content.find_by!(slug: params[:slug])
		sale = content.sales.create(
			amount: (content.price * 100).floor,
			email_acquirente: current_user.email,
			email_venditore: content.user.email,
			stripe_token: params[:stripeToken]	
			)
		sale.running!

		if sale.completed?
			redirect_to pickup_url(guid: sale.guid)
		else
			redirect_to content_path(content), notice: @error
		end
	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@content = @sale.content
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h4><b><%= pluralize(content.errors.count, "errori") %> non permettono al form di essere inviato</b></h4>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Carica il contenuto che vuoi vendere (Formati supportati: PowerPoint, Excel, Word, PDF, Immagini e MP3)</label>

    <br>

    <%= form.file_field :allegato %>
  </div>

  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_area :descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= form.label :prezzo_min_50_cent %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <label>Carica un'immagine da utilizzare come cover per il tuo contenuto</label>

    <br>

    <%= form.file_field :cover %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit 'Salva contenuto', class: "btn btn-form" %>
  </div>

  <br>

<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica contenuto <%= @content.titolo %></h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra contenuto', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<div class="row">
  <% @contents.each do |content| %>
    <div class="col s12 m6 l4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>
          <div>
            <span class="venditore">Venduto da <%= content.user.name %></span>
            <span class="right"><%= number_to_currency(content.price) %></span>
          </div>

          <br>

          <div class="center"><%= link_to 'Scopri di più', content, class: "btn" %></div>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">close</i></span>
          <p><%= content.descrizione %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
  <%= will_paginate @contents %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Vendi un contenuto</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<div class="content-show">
	<div class="row">
		<div class="col l6 show-img">
			<%= image_tag @content.cover.url, class: "responsive-img" %>
		</div>
		<div class="col l6">
			<h1 class="show-titolo"><%= @content.titolo %></h1>
			<h4 class="show-prezzo"><%= number_to_currency(@content.price) %></h4>
			<p>Venduto da <%= @content.user.name %></p>
			<p><%= @content.descrizione %></p>

			<% if current_user %>
				<%= form_tag compra_path(slug: @content.slug) do %>
					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
					      data-description="<%= @content.titolo %>"
					      data-email="<%= current_user.email %>"
					      data-currency="eur"
					      data-amount="<%= (@content.price * 100).floor %>"
					      data-name="LacerMarket"
					      data-locale="auto">
					</script>
				<% end %>
			<% else %>
				<p>Fai <%= link_to "Log In", new_user_session_path %> oppure <%= link_to "Registrati", new_user_registration_path %> per acuistare questo contenuto.</p>
			<% end %>
		</div>
	</div>



	<% if @content.user == current_user %>
		<%= link_to 'Edit', edit_content_path(@content) %> |
	<% end %>
	<%= link_to 'Torna ai contenuti', contents_path %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer red accent-1 center">
  <div class="footer-copyright">
    <div class="container">
		<div class="row">
			<div class="col s4">
				 © 2015 Lacerba.io
			</div>
			<div class="col s4">
				<a href="http://facebook.com/lacerba.io" target="_blank"><i class="fa-social fab fa-facebook-f white-text fa-2x"></i></a>
				<a href="http://twitter.com/lacerba_io" target="_blank"><i class="fa-social fab fa-twitter white-text fa-2x"></i></a>
			</div>
			<div class="col s4">
				<%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
			</div>
		</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="red accent-1">
    <div class="container nav-wrapper">
      <%= link_to '<i class="fas fa-tshirt"></i>'.html_safe, root_path %>
      <%= link_to 'LacerMarket', root_path, class: "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Vendi Contenuto', new_content_path %></li>
        <% if user_signed_in? %>
          <ul id="dropdown1" class="dropdown-content">
            <li><%= link_to 'Dashboard', dashboard_path %></li>
            <li><%= link_to 'Impostazioni', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><<%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Registrazione", new_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="sidenav" id="mobile-demo">
        <li><%= link_to 'Vendi Contenuto', new_content_path %></li>
        <% if user_signed_in? %>

            <li><%= link_to 'Dashboard', dashboard_path %></li>
            <li><%= link_to 'Impostazioni', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Registrazione", new_user_registration_path %></li>
        <% end %>
      </ul> 
    </div>
  </nav> 
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LacerMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <%= render "layouts/header" %>

    <%= render "pages/slider" if action_name == 'home' %>
    
    <main class="container">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>

  </body>
  
  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>
  <div>
    <% flash.each do |type, msg| %>
      <script>
        $(document).ready(function(){
          M.toast({html: "<%=msg%>", classes: 'rounded <%=type%>'});
        });
      </script>
    <% end %>
  </div>
  <script>
    $(document).ready(function(){
       $('.parallax').parallax();
    });
  </script>
  <script>
    $(document).ready(function(){
       $('.tabs').tabs();
    });
  </script>
  <script>
    $(document).ready(function(){
      $(".dropdown-trigger").dropdown();
    });
  </script>
</html>

app/views/pages/_slider.html.erb
<div class="center content-show">
	<% if @contents.count >0 %>
		<div class="carousel carousel-slider">
			<% @contents.each do |content| %>
					<%= link_to image_tag(content.cover.url), content_path(content), class: "carousel-item responsive-img" %>
			<% end %>
		</div>
		<br>
		<div class="row center">
	      <%= link_to 'Vai ai contenuti', contents_path, class: "btn red btn-large" %>
	    </div>
	<% else %>
		<div id="index-banner" class="parallax-container">
			<div class="section no-pad-bot">
			    <br><br>
			    <div class="row center">  	
			      <h1>LacerMarket</h1>
			      <h5>Vendi e acquista articoli di abbigliamento</h5>
			    </div>
			    <div class="row center">
			      <%= link_to 'Vai ai contenuti', contents_path, class: "btn red btn-large" %>
			    </div>
			    <br><br>

			</div>
		<div class="parallax"><%= image_tag("pexels-photo-1630344.jpeg") %></div>
		</div>
	<%end%>
</div>

app/views/pages/about.html.erb
<h1>Chi siamo</h1>
<p>Siamo un team  di ragazzi che insegna corsi startup</p>

app/views/pages/dashboard.html.erb
<h1 class="center"> Dashboard </h1>
<div class="row">
	<div class="col s12">
	  <ul class="tabs">
	    <li class="tab col s6"><a href="#storico">Storico</a></li>
	    <li class="tab col s6"><a href="#vendita">In vendita</a></li>
	  </ul>
	</div>
	<div id="storico" class="col s12">
		<h4><b>Vendite</b></h4>
		<table>
			<thead>
				<tr>
					<th>Nome</th>
					<th>Prezzo</th>
					<th>Data</th>
					<th>Acquirente</th>
				</tr>

			</thead>
			<tbody>
				<% @sales.each do |sale| %>
					<tr>
						<th><%= sale.content.titolo %></th>
						<th><%= number_to_currency(sale.amount / 100) %></th>
						<th><%= time_ago_in_words(sale.created_at) %> fa</th>
						<th><%= sale.email_acquirente %></th>
					</tr>
				<% end %>
			</tbody>
		</table>
		<br><br>
		<h4><b>Acquisti</b></h4>
		<table>
			<thead>
				<tr>
					<th>Nome</th>
					<th>Prezzo</th>
					<th>Data</th>
					<th>Venditore</th>
				</tr>

			</thead>
			<tbody>
				<% @purchased.each do |purchased| %>
					<tr>
						<th><%= link_to purchased.content.titolo, pickup_path(purchased.guid) %></th>
						<th><%= number_to_currency(purchased.amount / 100) %></th>
						<th><%= time_ago_in_words(purchased.created_at) %></th>
						<th><%= purchased.email_venditore %></th>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div id="vendita" class="col s12">
		<table>
			<thead>
				<tr>
					<th>Nome</th>
					<th>Prezzo</th>
					<th>Data di creazione</th>
					<th>Azioni</th>
				</tr>

			</thead>
			<tbody>
				<% @content.each do |content| %>
					<tr>
						<th><%= link_to content.titolo, content_path(content) %></th>
						<th><%= number_to_currency(content.price) %></th>
						<th><%= time_ago_in_words(content.created_at) %> fa</th>
						<th><%= link_to 'Modifica',edit_content_path(content) %> | <%= link_to 'Elimina', content, method: :delete, data: {confirm: 'Sei sicuro di eliminare questo contenuto?' } %></th>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/pages/home.html.erb
<div class="center">
	<h2 class="home-subtitle">Negozio online di abbigliamento</h2>
	<div class="row">
		<div class="col s12 m4">
			<h2 class="center"><i class="material-icons medium">shopping_basket</i></h2>
			<h5 class="center">Shop</h5>
			<p class="center">Acquista e vendi i tuoi articoli.</p>
		</div>
		<div class="col s12 m4">
			<h2 class="center"><i class="material-icons medium">people_outline</i></h2>
			<h5 class="center">Community</h5>
			<p class="center">Condividi opinioni con gli altri utenti.</p>
		</div>
		<div class="col s12 m4">
			<h2 class="center"><i class="material-icons medium">apps</i></h2>
			<h5 class="center">App</h5>
			<p class="center">Utilizza l'App per connetterti in qualunque momento.</p>
		</div>
	</div>
</div>
<script>
	$('.carousel.carousel-slider').carousel({
    	fullWidth: true
  	});
</script>

app/views/transactions/pickup.html.erb
<h1>Grazie per aver acquistato <%= @content.titolo %></h1>

<p><%= link_to "Scarica qui", @content.allegato.url %> il tuo contenuto.</p>